# docker-compose.yml
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      FRONTEND_URL: http://localhost:3001
      DATABASE_URL: postgres://user:password@db:5432/contactdb
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: contactdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
      # Add this line to run the initialization script
      - ./initdb:/docker-entrypoint-initdb.d # This is a special directory PostgreSQL looks for
    restart: unless-stopped

volumes:
  db-data:
