# docker-compose.yml

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env # Load all app-related env vars from the local .env file
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    env_file:
      - ./.env # Load all db-related env vars from the local .env file
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  db-data:
